spring.application.name=agenda-api

spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_db
spring.datasource.username=postgres
spring.datasource.password=Giul20@03

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
