spring.application.name=vet-clinic-api

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:minha-chave-secreta-muito-segura-para-jwt-256-bits-12345}
jwt.expiration=86400000
